### PR TITLE
add BytesAudioSourceManager

### PR DESCRIPTION
**Pull request by katstack**
add support to playing bytes for like Text To Speech

### CODE REVIEW

**Comment by Walkyst** [comment]
Can you provide some examples how this can be used so i can test it myself

**Comment by katstack** [comment]
almost copy of LocalAudioSourceManager

[check this example](https://gist.github.com/Whya5448/9fce69979661b20bd831a542d92c3f97.js
)

[or this](https://github.com/Walkyst/lavaplayer-fork/blob/original/main/src/test/groovy/com/sedmelluq/discord/lavaplayer/integration/PlayerManagerTestTools.java)

**Review by Hydro001 — APPROVED** [review]

**Review by JellyBrick — APPROVED** [review]

**Comment by DxsSucuk** [comment]
@Walkyst anything else needed or will this be merged?

**Comment by Hydro001** [comment]
As DxsSucuk said, is this going to be merged or does it requires any changes ?

**Comment by Walkyst** [comment]
At some point, when I will have time to review this

**Comment by Hydro001** [comment]
> At some point, when I will have time to review this

No problem, thanks for maintaining this awesome project by the way 👍

**Comment by DxsSucuk** [comment]
Damn this PR takes some long ass time.
Any updates?

**Pull request closed without merging**
